site_name: FFS

# Meta tags (placed in header).
site_description: FFS is a fast and lean open-source platform for managing and deploying feature flags.
site_author: Doist
site_url: https://github.com/Doist/ffs

# Repository (add link to repository on each page).
repo_name: Doist/ffs
repo_url: https://github.com/Doist/ffs
edit_uri: edit/main/docs/src

# Copyright (shown at the footer).
copyright: 'Copyright &copy; 2022 Doist'

# Material theme.
theme:
  favicon: _assets/favicon.ico
  logo: _assets/icon-192.png
  name: 'material'
  custom_dir: theme
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/lightbulb
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Light mode
  social:
    - type: 'github'
      link: 'https://github.com/Doist/ffs'
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top

# Plugins and extensions.
plugins:
  - awesome-pages
  - search
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets

# Navigation.
docs_dir: src
nav:
  - Home: index.md
  - Feature flags:
    - feature-flags/index.md
    - Anatomy of rules: feature-flags/anatomy-of-rules.md
    - Time to live: feature-flags/time-to-live.md
    - Archiving: feature-flags/archiving.md
  - Dashboard:
    - dashboard/index.md
    - Users: dashboard/users.md
    - Organizatins and projects: dashboard/organizations-and-projects.md
    - API tokens: dashboard/api-tokens.md
    - Feature flags: dashboard/feature-flags.md
    - Authorization: dashboard/authorization.md
  - SDKs:
    - sdks/index.md
    - JavaScript: sdks/javascript.md
    - Kotlin: sdks/kotlin.md
    - Swift: sdks/swift.md
    - Python: sdks/python.md
    - Ruby: sdks/ruby.md
    - Rust: sdks/rust.md
    - Go: sdks/go.md
  - Server:
    - server/index.md
    - Running: server/running.md
    - Configuration: server/configuration.md
  - API:
    - api/index.md # mention authorization via users (org-wide) or tokens (project-specific).
    - Users: api/users.md
    - Organizations: api/organizations.md
    - Projects: api/projects.md
    - Flags: api/flags.md
    - Tokens: api/tokens.md
  - Changelog: changelog.md
  - Reference: dokka/index.html
