name: Publish documentation
on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'CHANGELOG.md' ]

jobs:
  build:
    name: Publish documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: ./gradlew mkdocsPublish
