name: Scan code with detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 6 * * 1'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: ./gradlew detekt
      - uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: build/reports/detekt/merge.sarif
